manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=esp32,esp32s3,esp32c6,esp32p4
id=tactility.diceware
version.name=0.15.0
version.code=15
name=Diceware
description=Password generator
app.0.id=tactility.diceware
app.0.name=Diceware
app.0.binary=diceware
