manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=esp32s3,esp32p4
id=tactility.m5unittest
version.name=0.11.0
version.code=11
app.0.id=tactility.m5unittest
app.0.name=M5 Unit Test
app.0.binary=m5unittest
