name: Publish Apps

inputs:
  sdk_version:
    description: The SDK version that determines the path on the CDN
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Download cdn-files'
      uses: actions/download-artifact@v4
      with:
        name: 'cdn-files'
        path: cdn_files
    - name: 'Install boto3'
      shell: bash
      run: pip install boto3
    - name: 'Upload files'
      shell: bash
      run: python Buildscripts/CDN/upload-app-files.py cdn_files ${{ inputs.sdk_version }} ${{ env.CDN_ID }} ${{ env.CDN_TOKEN_NAME }} ${{ env.CDN_TOKEN_VALUE }}
