manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=esp32,esp32s3,esp32c6,esp32p4
id=tactility.snake
version.name=0.16.0
version.code=16
description=Classic Snake game
app.0.id=tactility.snake
app.0.name=Snake
app.0.binary=snake
