manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=esp32,esp32s3,esp32c6,esp32p4,posix-x86_64
id=tactility.tone
version.name=0.1.0
version.code=1
name=Tone
description=Tone generator and frequency sweeper
app.0.id=tactility.tone
app.0.name=Tone
app.0.binary=tone