manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=esp32,esp32s3,esp32c6,esp32p4,posix-x86_64
id=tactility.helloworld
version.name=0.13.0
version.code=13
name=Hello World
app.0.id=tactility.helloworld
app.0.name=Hello World
app.0.binary=helloworld
