manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=esp32,esp32s3,esp32c6,esp32p4,posix-x86_64
id=tactility.busyboxvi
version.name=0.1.0
version.code=1
name=Vi
description=BusyBox vi text editor
app.0.id=tactility.busyboxvi
app.0.name=BusyBox vi
app.0.binary=vi
app.0.hidden=true
app.0.headless=true
app.0.stack.depth=4096
