manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=posix-x86_64,esp32s3
id=tactility.coreutils
version.name=0.2.0
version.code=2
name=CoreUtils
description=Commandline utilities
app.0.id=tactility.coreutils.echo
app.0.name=Echo
app.0.binary=echo
app.0.hidden=true
app.1.id=tactility.coreutils.date
app.1.name=Date
app.1.binary=date
app.1.hidden=true
