manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=esp32s3,esp32p4
id=tactility.epubreader
version.name=0.12.0
version.code=12
description=Epub and text file reader. Requires PSRAM!
app.0.id=tactility.epubreader
app.0.name=Epub Reader
app.0.binary=epubreader
