manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=esp32,esp32s3,esp32c6,esp32p4
id=tactility.mystifydemo
version.name=0.14.0
version.code=14
name=Mystify Demo
description=A graphics demo that is inspired by a Windows 95 screensaver.
app.0.id=tactility.mystifydemo
app.0.name=Mystify Demo
app.0.binary=mystifydemo
