manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=esp32,esp32s3,esp32c6,esp32p4
id=tactility.tamatac
version.name=0.11.0
version.code=11
name=TamaTac
description=Virtual pet inspired by Tamagotchi. Only runs on devices with PSRAM.
app.0.id=tactility.tamatac
app.0.name=TamaTac
app.0.binary=tamatac
