manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=esp32,esp32s3,esp32c6,esp32p4,posix-x86_64
id=tactility.rcc700
version.name=0.1.0
version.code=1
requires.ram=2M
name=rcc700
description=Mini C compiler for ESP32 RISC-V
app.0.id=tactility.rcc700
app.0.name=rcc700
app.0.binary=rcc700
app.0.hidden=true
app.0.headless=true
app.0.stack.depth=16384
app.0.cleanup=true
