manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=esp32,esp32s3,esp32c6,esp32p4
id=tactility.graphicsdemo
version.name=0.13.0
version.code=13
name=Graphics Demo
app.0.id=tactility.graphicsdemo
app.0.name=Graphics Demo
app.0.binary=graphicsdemo
