manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=esp32p4
id=tactility.doom
version.name=0.6.0
version.code=6
name=Doom
description=Classic DOOM. Tab5 only, keyboard required to play.
app.0.id=tactility.doom
app.0.name=Doom
app.0.binary=doom
requires.device.id=m5stack-tab5
