manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=esp32s3,esp32p4
id=tactility.mediakeys
version.name=0.13.0
version.code=13
name=Media Keys
description=Bluetooth media keys. Touch or Physical Keyboard control\nB - previous, P - play/pause, N - next, M - mute, D - volume down, U - volume up.\nQ or ESC to exit focus.
app.0.id=tactility.mediakeys
app.0.name=Media Keys
app.0.binary=mediakeys
