manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=esp32,esp32s3,esp32c6,esp32p4
id=tactility.todolist
version.name=0.14.0
version.code=14
description=Simple task list manager
app.0.id=tactility.todolist
app.0.name=Todo List
app.0.binary=todolist
