manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=esp32,esp32s3,esp32c6,esp32p4
id=tactility.serialconsole
version.name=0.15.0
version.code=15
app.0.id=tactility.serialconsole
app.0.name=Serial Console
app.0.binary=serialconsole
