manifest.version=0.3
target.sdk=0.8.0-dev
target.platforms=esp32,esp32s3,esp32c6,esp32p4
id=tactility.gpio
version.name=0.15.0
version.code=15
app.0.id=tactility.gpio
app.0.name=GPIO
app.0.binary=gpio
